### ISSUE TITLE
Add Proxy???

### ISSUE THREAD

**Issue by cubanitoalex** [Crusta/Crusta.Droid#1]
You can add an internal option for proxy server and port

**Comment by Tarptaeya** [comment]
Thanks, does https://github.com/Crusta/Crusta.Droid/commit/43f2f62835c097b758f44632b9b6640166a690f3 serves your purpose?


<img width="250" src="https://user-images.githubusercontent.com/22481002/63330719-eac42080-c351-11e9-87c1-faaf0d25b519.png">

**Comment by cubanitoalex** [comment]
Perfect that same, thanks for answering.
